services:
  - type: web
    name: remote-interview-portal
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false # User will input their MongoDB Connection String in Render dashboard
      - key: JWT_SECRET
        generateValue: true # Generates a secure random JWT secret key automatically
      - key: GEMINI_API_KEY
        sync: false # User will input their Gemini API Key in Render dashboard
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        sync: false # User will input their Gmail account in Render dashboard
      - key: SMTP_PASS
        sync: false # User will input their Gmail App Password in Render dashboard
      - key: BREVO_API_KEY
        sync: false # User will input their Brevo API Key in Render dashboard
