const express = require('express');
const router = express.Router();
const { protect } = require('../middleware/auth');
const MockInterviewSession = require('../models/MockInterviewSession');
const Category = require('../models/Category');
const { generateAIQuestions } = require('../utils/gemini');

// Helper to return high-quality fallback questions in case of API rate limits
const getLocalFallbackMockQuestions = (categoryName, count) => {
    const backups = [
        { questionText: `Explain the concept of inheritance and polymorphism in Object-Oriented Programming.`, idealAnswer: `Inheritance allows a class to inherit properties and methods from another class. Polymorphism allows methods to do different things based on the object acting upon them.` },
        { questionText: `How do you identify and resolve performance bottlenecks in a slow application?`, idealAnswer: `Use profilers, monitor DB query execution times, optimize nested loops, implement caching (like Redis), and minimize payload sizes.` },
        { questionText: `What is the role of continuous integration and continuous deployment (CI/CD) in software development?`, idealAnswer: `CI/CD automates building, testing, and deploying code, reducing human error and speeding up product delivery cycles.` },
        { questionText: `How do you handle error states and exception management in your codebase?`, idealAnswer: `Utilize global error boundaries, write clean try-catch exception handling, log errors on the server, and display clean status responses to the user.` },
        { questionText: `Describe the difference between state and props in modern web frameworks.`, idealAnswer: `Props are read-only properties passed down from a parent component. State is local, mutable data managed within the component itself.` }
    ];
    
    return backups.slice(0, count).map((q, idx) => ({
        _id: `mock_fallback_${idx}_${Date.now()}`,
        questionText: q.questionText,
        idealAnswer: q.idealAnswer,
        tips: ["Be precise with technical terms", "Structure your logic step-by-step"],
        difficulty: "Medium",
        timeLimit: 120,
        interviewType: categoryName
    }));
};

// @route   GET /api/mock/questions
// @desc    Get mock interview questions generated by AI (Gemini)
router.get('/questions', protect, async (req, res) => {
    try {
        const { categoryId } = req.query;

        if (!categoryId) {
            return res.status(400).json({
                success: false,
                message: 'categoryId is required'
            });
        }

        const category = await Category.findById(categoryId);
        if (!category) {
            return res.status(404).json({ success: false, message: 'Category not found' });
        }

        // Generate 5 questions dynamically using Gemini AI
        let questions = [];
        const difficulty = 'Medium';
        const questionsCount = 5;

        try {
            const rawQuestions = await generateAIQuestions(category.name, difficulty, questionsCount);
            questions = rawQuestions.map((q, idx) => ({
                _id: `mock_ai_${idx}_${Date.now()}`,
                questionText: q.questionText,
                idealAnswer: q.idealAnswer,
                tips: q.tips,
                difficulty,
                timeLimit: 120,
                interviewType: category.name
            }));
        } catch (geminiError) {
            console.error('Gemini mock question generation failed, falling back to static database questions:', geminiError);
            try {
                const Question = require('../models/Question');
                const dbQuestions = await Question.find({ categoryId, isActive: true });
                if (dbQuestions && dbQuestions.length > 0) {
                    // Pick 5 random questions from the 10 seeded ones
                    const shuffled = dbQuestions.sort(() => 0.5 - Math.random());
                    questions = shuffled.slice(0, questionsCount).map(q => ({
                        _id: q._id,
                        questionText: q.questionText,
                        idealAnswer: q.idealAnswer,
                        tips: q.tips,
                        difficulty: q.difficulty,
                        timeLimit: q.timeLimit || 120,
                        interviewType: category.name
                    }));
                } else {
                    questions = getLocalFallbackMockQuestions(category.name, questionsCount);
                }
            } catch (dbError) {
                console.error('Database fallback queries failed, using hardcoded static fallback:', dbError);
                questions = getLocalFallbackMockQuestions(category.name, questionsCount);
            }
        }

        res.status(200).json({
            success: true,
            count: questions.length,
            data: questions
        });
    } catch (error) {
        console.error('Error fetching mock questions:', error);
        res.status(500).json({ success: false, message: 'Server error' });
    }
});

// @route   POST /api/mock/submit
// @desc    Record a mock interview session
router.post('/submit', protect, async (req, res) => {
    try {
        const {
            interviewType,
            confidenceScore,
            hasVideo,
            videoUrl,
            videoDuration,
            feedback,
            overallScore,
            communicationScore,
            technicalScore,
            questionsAsked,
            questionsCorrect,
            duration,
            strengths,
            improvementAreas,
            recordings
        } = req.body;

        const session = await MockInterviewSession.create({
            userId: req.user.id,
            interviewType,
            confidenceScore,
            hasVideo: hasVideo || false,
            videoUrl: videoUrl || null,
            videoDuration: videoDuration || 0,
            feedback,
            overallScore: overallScore || 0,
            communicationScore: communicationScore || 0,
            technicalScore: technicalScore || 0,
            questionsAsked: questionsAsked || 0,
            questionsCorrect: questionsCorrect || 0,
            duration: duration || 0,
            strengths: strengths || [],
            improvementAreas: improvementAreas || [],
            recordings: recordings || []
        });

        res.status(201).json({ success: true, data: session });
    } catch (error) {
        console.error('Error saving mock session:', error);
        res.status(500).json({ success: false, message: 'Server error' });
    }
});

// @route   POST /api/mock/upload-video
// @desc    Upload recorded interview question video
router.post('/upload-video', protect, express.raw({ type: 'video/webm', limit: '50mb' }), async (req, res) => {
    try {
        const fs = require('fs');
        const path = require('path');

        if (!req.body || req.body.length === 0) {
            return res.status(400).json({ success: false, message: 'No video data received' });
        }

        const os = require('os');
        const uploadsDir = path.join(os.tmpdir(), 'interview-portal-uploads');
        if (!fs.existsSync(uploadsDir)) {
            fs.mkdirSync(uploadsDir, { recursive: true });
        }

        const fileName = `video-${req.user.id}-${Date.now()}.webm`;
        const filePath = path.join(uploadsDir, fileName);

        fs.writeFileSync(filePath, req.body);

        const videoUrl = `/uploads/${fileName}`;

        res.status(200).json({
            success: true,
            videoUrl
        });
    } catch (error) {
        console.error('Error uploading video:', error);
        res.status(500).json({ success: false, message: 'Server error' });
    }
});

// @route   GET /api/mock/sessions
// @desc    Get all mock sessions for a user
router.get('/sessions', protect, async (req, res) => {
    try {
        const sessions = await MockInterviewSession.find({ userId: req.user.id }).sort('-createdAt');
        res.status(200).json({ success: true, count: sessions.length, data: sessions });
    } catch (error) {
        res.status(500).json({ success: false, message: 'Server error' });
    }
});

module.exports = router;
